### ISSUE TITLE
The application of blank node identifiers

### ISSUE THREAD

**Issue by tplooker** [w3c/vc-di-bbs#10]
In RDF canonicalisation/normalisation, one of the trickiest parts of the algorithm is dealing with [blank nodes](https://json-ld.github.io/normalization/spec/index.html#dfn-blank-node). [RDF Data Set Normalisation](https://json-ld.github.io/normalization/spec/index.html) defines a way in which to allocate identifiers for blank nodes deterministically for normalization.

However the algorithm does not guarantee that the same blank node identifiers will be allocated in the event of modifications to the graph.

For example

The following JSON-LD normalized 

```
{
    "@context": [ "http://schema.org/",
                  "https://w3id.org/security/v2" ],
    "firstName": "Jane",
    "lastName": "Does",
    "jobTitle": "Professor",
    "telephone": "(425) 123-4567",
    "email": "jane.doe@example.com",
    "address": {
      "postalAddress": "test"
     }
}
```

Yields

```
_:c14n0 <http://schema.org/postalAddress> "test" .
_:c14n1 <http://schema.org/address> _:c14n0 .
_:c14n1 <http://schema.org/email> "jane.doe@example.com" .
_:c14n1 <http://schema.org/firstName> "Jane" .
_:c14n1 <http://schema.org/jobTitle> "Professor" .
_:c14n1 <http://schema.org/lastName> "Does" .
_:c14n1 <http://schema.org/telephone> "(425) 123-4567" .
```

Where we have two blank nodes `_:c14n0` and `_:c14n1`.

If we then remove the address from the original JSON-LD i.e like below

```
{
    "@context": [ "http://schema.org/",
                  "https://w3id.org/security/v2" ],
    "firstName": "Jane",
    "lastName": "Does",
    "jobTitle": "Professor",
    "telephone": "(425) 123-4567",
    "email": "jane.doe@example.com"
}
```

We get different blank node identifiers for the same statements shown above.

```
_:c14n0 <http://schema.org/email> "jane.doe@example.com" .
_:c14n0 <http://schema.org/firstName> "Jane" .
_:c14n0 <http://schema.org/jobTitle> "Professor" .
_:c14n0 <http://schema.org/lastName> "Does" .
_:c14n0 <http://schema.org/telephone> "(425) 123-4567" .
```

Why is this a problem?

Because bbs-signatures aim to create selective disclosure of statements i.e revealing only a portion of the originally signed data graph and we must prove the integrity of revealed statements to show they were originally signed by the issuer.
 
Because we are often revealing only a subset of statements from the original, we must have a way in which guarantees that the node identifiers of the normalized statements being revealed  match those that were originally signed.

**Solution 1**

When producing a BBS Signature we use the blank node identifier algorithm to allocate blank node identifiers, which we then transform into proper node identifiers, (E.g _:c14n1 => urn:bnid:_:c14n1) for which we then sign the resulting statements, see below for an example.

Given the input JSON-LD document to signed

```
{
    "@context": [ "http://schema.org/",
                  "https://w3id.org/security/v2" ],
    "firstName": "Jane",
    "lastName": "Does",
    "jobTitle": "Professor",
    "telephone": "(425) 123-4567",
    "email": "jane.doe@example.com",
    "address": {
      "postalAddress": "test"
    }
}
```

We normalize

```
_:c14n0 <http://schema.org/postalAddress> "test" .
_:c14n1 <http://schema.org/address> _:c14n0 .
_:c14n1 <http://schema.org/email> "jane.doe@example.com" .
_:c14n1 <http://schema.org/firstName> "Jane" .
_:c14n1 <http://schema.org/jobTitle> "Professor" .
_:c14n1 <http://schema.org/lastName> "Does" .
_:c14n1 <http://schema.org/telephone> "(425) 123-4567" .
```

Then transform any node identifiers to proper ones to get our input into signing

```
<urn:bnid:_:c14n0> <http://schema.org/postalAddress> "test" .
<urn:bnid:_:c14n1> <http://schema.org/address> <urn:bnid:_:c14n0> .
<urn:bnid:_:c14n1> <http://schema.org/email> "jane.doe@example.com" .
<urn:bnid:_:c14n1> <http://schema.org/firstName> "Jane" .
<urn:bnid:_:c14n1> <http://schema.org/jobTitle> "Professor" .
<urn:bnid:_:c14n1> <http://schema.org/lastName> "Does" .
<urn:bnid:_:c14n1> <http://schema.org/telephone> "(425) 123-4567" .
```

We then take the normalized from and cast it back to JSON-LD with the allocated blank node identifiers

```
{
    "@context": [ "http://schema.org/",
                  "https://w3id.org/security/v2" ],
    "id": "urn:bnid:_:c14n1",
    "firstName": "Jane",
    "lastName": "Does",
    "jobTitle": "Professor",
    "telephone": "(425) 123-4567",
    "email": "jane.doe@example.com",
    "address": {
      "id": "urn:bnid:_:c14n0",
      "postalAddress": "test"
    },
    { 
    "type": "BbsBlsSignature2020",
    "created": "2020-04-18T05:26:47Z",
    "revealedStatements": [ 1, 3 ],
    "verificationMethod": "did:example:489398593#test",
    "proofPurpose": "assertionMethod",
    "signature":  "BAXSgt7mVHjjpH6H......" 
  } 
}
```

This means when we are creating a sub-graph we have the allocated identifiers for the formerly blank nodes allocated.

E.g given the above digital signature, the following proof could be derived.

```
{
    "@context": [ "http://schema.org/",
                  "https://w3id.org/security/v2" ],
    "id": "urn:bnid:_:c14n1",
    "firstName": "Jane",
    "lastName": "Does",
    { 
    "type": "BbsBlsSignatureProof2020",
    "verificationMethod": "did:example:489398593#test",
    "proofPurpose": "assertionMethod",
    "proof":  "BAXSgt7mVHjjpH6H......" ,
    "requiredRevealStatements": [ 1, 3 ],
    "revealedStatements": [ 1, 3 ],
    "totalStatements": 10,
  } 
}
```

**Comment by tplooker** [comment]
An alternative proposal suggested by @dlongley is to have a mapping for any BN identifiers in the proof to prevent the need for special skolem URIs (e.g `urn:bnid:_:c14n1`).

This mapping must map the blank node identifiers allocated to the statements in the canonical form of the derivedProof back to what their blank node identifiers were in the originally signed proof.

Because all blank nodes have a common prefix e.g `_:c14n*` we essentially only need a map between the numbers assigned to the blank nodes for example mapping from `_:c14n1` => `_:c14n0` could be shorthanded to 1 => 0.

How we express this in the proof we could do in one of two ways.

1. An ordered array of signed integers, where the index in the array represents the blank node id in the derived proof and the value is the blank node id in the original proof, this would result in something like the following.

```
{
    .....data graph for which the proof applies to
    { 
    "type": "BbsBlsSignatureProof2020",
    "verificationMethod": "did:example:489398593#test",
    "proofPurpose": "assertionMethod",
    "proof":  "BAXSgt7mVHjjpH6H......" ,
    "requiredRevealStatements": [ 1, 3 ],
    "revealedStatements": [ 1, 3 ],
    "totalStatements": 10,
    "blankNodeIdentiferMap": [
         1,
         0,
         2,
         3
    ]
  } 
}
```

2. A map, where the key represents the blank node id in the derived proof and the value is the blank node id in the original proof, this would result in something like the following.

```
{
    .....data graph for which the proof applies to
    { 
    "type": "BbsBlsSignatureProof2020",
    "verificationMethod": "did:example:489398593#test",
    "proofPurpose": "assertionMethod",
    "proof":  "BAXSgt7mVHjjpH6H......" ,
    "requiredRevealStatements": [ 1, 3 ],
    "revealedStatements": [ 1, 3 ],
    "totalStatements": 10,
    "blankNodeIdentiferMap": {
         "0": 1,
         "1": 0,
         "2": 2,
         "3": 3
    }
  } 
}
```

@dlongley is this an accurate summary of the idea you had in mind?

**Comment by dlongley** [comment]
@tplooker,

> @dlongley, is this an accurate summary of the idea you had in mind?

Yes. I also think that the mapping could be embedded in the `proofValue` -- allowing for some more compact representation, i.e., it doesn't have to be broken out at the JSON level.

**Comment by tplooker** [comment]
@dlongley Ah interesting that would further simplify the representation, we will review that as an idea

**Comment by tplooker** [comment]
@dlongley did you have any thoughts on how this binary encoding should be done? I.e a custom binary format or should we be using a more formalised method like protocol buffers or message pack?

The simplest way I see doing this would be somthing of the following

proofValue : "`base64(int16(blankNodeIdentiferMap.length)|int16(blankNodeIdentiferMap[0])..|..int16(blankNodeIdentiferMap[blankNodeIdentiferMap.length])|remainingProofValueOutputedByDeriveProofAPI)"

Where `|` is indicating concatenation `blankNodeIdentiferMap` is the unsigned int array described in the example above.

**Comment by dlongley** [comment]
My vote for binary representations is CBOR. There is likely to be significant work in the future on CBOR-LD (including representing VCs using that format) and it would be best not to introduce yet another competing format with protocol buffers/etc.

**Comment by kdenhartog** [comment]
@TimoGlastra said during IIW that he was going to take this issue.

**Comment by TimoGlastra** [comment]
@kdenhartog RE your note in #37. I just discovered you can only assign outside collaborators when they've commented. So here's my comment

**Comment by OR13** [comment]
Can we fold this into #60? I am going to mark it bending close.

**Comment by Wind4Greg** [comment]
Please see the updated document for mechanism details that address these concerns. See PR https://github.com/w3c/vc-di-bbs/pull/101 for privacy considerations related to both data leakage and unlinkability, including analysis.
