### ISSUE TITLE
Handling/encoding of nonMandatory and bbsMessages

### ISSUE THREAD

**Issue by aphillips** [w3c/vc-di-bbs#111]
3.2.3 createDisclosureData
https://www.w3.org/TR/vc-di-bbs/#createdisclosuredata

> Initialize bbsMessages to an array of byte arrays obtained from the UTF-8 encoding of the the values in the nonMandatory array. 

https://www.w3.org/TR/vc-di-bbs/#base-proof-serialization-bbs-2023

> Initialize bbsMessages to an array of byte arrays obtained from the UTF-8 encoding of the the values in the nonMandatory array. 

The value of `bbsMessages` is encoded (and later decoded) as an array of byte arrays using the UTF-8 encoding. Missing from this is a description of `nonMandatory` as being an array of strings (presumably Unicode strings?). These bits of text could be a bit tighter, for example:

> Initialize `bbsMessages` to an array of byte arrays containing the values in the `nonMandatory` array of strings encoded using the UTF-8 character encoding.

Linking to UTF-8 and 'character encoding' in the I18N glossary might also be helpful here.

**Comment by msporny** [comment]
PR #115 was raised to address this issue and has been merged, closing.
