### ISSUE TITLE
Specify byte or character value of `u`

### ISSUE THREAD

**Issue by aphillips** [w3c/vc-di-bbs#113]
3.2.2 parseBaseProofValue
https://www.w3.org/TR/vc-di-bbs/#parsebaseproofvalue

> Ensure the proofValue string starts with `u`, indicating that it is a mult...

This section and a couple of others refer to values such as `u` and `b` in the context of byte arrays. There is no reference to the byte value or character encoding of the fields in question (these appear to be binary goo). Adding either a byte value reference or naming the character formally using Unicode notation would help ensure clarity.

See: https://www.w3.org/TR/international-specs/#char_ref

**Comment by Wind4Greg** [comment]
Hi @aphillips, looking at https://www.w3.org/TR/international-specs/#char_ref do you recommend I use the "character naming template" like in their [Example 7](https://www.w3.org/TR/international-specs/#example-example-of-a-character-reference) when writing a PR to address this?

Thanks Greg B.

**Comment by aphillips** [comment]
Thanks @Wind4Greg, yes, that's probably the best choice.

**Comment by msporny** [comment]
PR #115 was raised to address this issue and has been merged, closing.
