### ISSUE TITLE
Add note that implementers can reuse `createHmacIdLabelMapFunction` in `createShuffledIdLabelMapFunction`

### ISSUE THREAD

**Issue by dlongley** [w3c/vc-di-bbs#119]
Step 2 of this: https://w3c.github.io/vc-di-bbs/#createshuffledidlabelmapfunction

Just reuses this: https://w3c.github.io/vc-di-ecdsa/#createhmacidlabelmapfunction from vc-di-ecdsa.

So we should let implementers know that they can call that with the same `hmac` parameter before outputting the function that is returned -- and use it internally in that function to perform step 2.

**Comment by Wind4Greg** [comment]
@dlongley Do you mean step 1.2 in each of these algorithms?  Step 2 is just a return call.

So after the algorithm description add an informative note saying:

"It should be noted that step 1.2 in the above algorithm is identical to step 1.2 in  https://w3c.github.io/vc-di-ecdsa/#createhmacidlabelmapfunction so developers may be able to reuse the code if implementing both."

Or suggest some better text.

**Comment by dlongley** [comment]
Yeah, sorry I meant Step 1.2 as you say. It's really 1.1+1.2 ... we could just get `bnodeIdMap` from running that other function. Slight tweak to your suggestion:

> "It should be noted that step 1.2 in the above algorithm is identical to step 1.2 in https://w3c.github.io/vc-di-ecdsa/#createhmacidlabelmapfunction so developers may be able to reuse the code or call the function if implementing both."

**Comment by dlongley** [comment]
This was my issue and it was addressed by #130, closing.
