### ISSUE TITLE
Include issuer's original public key, `PK` in the base proof

### ISSUE THREAD

**Issue by dlongley** [w3c/vc-di-bbs#125]
We can eliminate a potential tracking vector (and the need to mitigate it) if we include the issuer's public key in the base proof instead of requiring holders to fetch it whenever they want to create a disclosure proof. I recommend we do this, even if it bloats the base proof size by 96 bytes -- as the base proof is only stored and not itself later transmitted during presentation to a verifier.

**Comment by dlongley** [comment]
I recommend we put `publicKey` (holding the 96-byte serialized `PK` value -- canonical compressed G2 point per the BBS spec) right after `bbsSignature` in the serialized base proof data (which is where the ECDSA ephemeral public key is for that scheme following its `baseSignature`).

**Comment by Wind4Greg** [comment]
That makes sense to me. I've been to use to did:key or generating test vectors to remember that they need the PK as part of BBS `proofGen` procedure. To me its also an efficiency thing, saving round trips across the network. They always need the PK to generate "derived proofs" so why not send it with the base proof. 

I saw  some other issues that may want to add to the proof serialization. Let me see if I can roll them together.

**Comment by dlongley** [comment]
This was my issue and it was addressed by #131, closing.
