### ISSUE TITLE
Outdated reference in the spec

### ISSUE THREAD

**Issue by iherman** [w3c/vc-di-bbs#132]
The introduction of the specification still uses the [[RDF-DATASET-NORMALIZATION](https://www.w3.org/TR/vc-di-bbs/#bib-rdf-dataset-normalization)] reference, which is obsolete by now (and should definitely not be a normative reference). As everywhere else in the document, [[RDF-CANON](https://www.w3.org/TR/vc-di-bbs/#bib-rdf-canon)] should be used.

**Comment by msporny** [comment]
PR #133 was raised to address this issue and has been merged, closing.
