### ISSUE TITLE
Specification should clearly identify BBS+ (not BBS)

### ISSUE THREAD

**Issue by msporny** [w3c/vc-di-bbs#136]
The specification should clearly state that BBS+ is the cryptography being used. I've been exchanging emails with someone that was concerned that we were using BBS and not BBS+. I started to tell them that the spec is clear that we're using BBS+, but they noted that it was not... a quick check of the spec didn't seem to indicate anything related to BBS+ was being used. We should make this more clear in the spec.

**Comment by dlongley** [comment]
The scheme used in this spec is described as "The BBS Signature Scheme", not "BBS+":

https://www.ietf.org/archive/id/draft-irtf-cfrg-bbs-signatures-05.html

**Comment by dlongley** [comment]
For more details:

> **The name BBS is derived from the authors of the original academic work by Dan Boneh, Xavier Boyen, and Hovav Shacham [[BBS04](https://www.ietf.org/archive/id/draft-irtf-cfrg-bbs-signatures-05.html#BBS04)], where the scheme was first described as part of a group signatures protocol. Soon after, the scheme was described by Camenisch and Lysyanskaya as a stand-alone signatures scheme in [[CL04](https://www.ietf.org/archive/id/draft-irtf-cfrg-bbs-signatures-05.html#CL04)], for anonymous credentials applications. Later, Au, Susilo an Mu presented the first, provably secure version of BBS Signatures in [[ASM06](https://www.ietf.org/archive/id/draft-irtf-cfrg-bbs-signatures-05.html#ASM06)]. Following, works by Camenisch, Drijvers and Lehmann [[CDL16](https://www.ietf.org/archive/id/draft-irtf-cfrg-bbs-signatures-05.html#CDL16)] and by Barki, Brunet, Desmoulins and Traore [[BBDT16](https://www.ietf.org/archive/id/draft-irtf-cfrg-bbs-signatures-05.html#BBDT16)], proved the security of the scheme in settings where more efficient computations are possible, thereby improving performance. Finally, in 2023, Tessaro and Zhu, presented in [[TZ23](https://www.ietf.org/archive/id/draft-irtf-cfrg-bbs-signatures-05.html#TZ23)] further performance improvements, shrinking the BBS signature. This document is mainly based on that work.**

The "BBS+" name, I believe, is from the work in the middle there from Au, Susilo and Mu. This was the first provably secure BBS scheme. Further work improved upon this and produced still provably-secure signatures but they were made shorter -- done by Tessaro and Zhu:

https://link.springer.com/chapter/10.1007/978-3-031-30589-4_24

From that paper:

> BBS+ signatures consist of one group element and two scalars. As our first contribution, we prove that a variant of BBS+ producing shorter signatures, consisting only of one group element and one scalar, is also secure. The resulting scheme is essentially the original BBS proposal, which was lacking a proof of security. Here we show it satisfies, under the q-SDH assumption, the same provable security guarantees as BBS+.

So the work here is not "BBS+" but a further improvement beyond it that goes back to using the original BBS proposal (with its benefits) but it is also provably secure.

**Comment by brentzundel** [comment]
I don't think we should say BBS+ since the dependent spec for DI-BBS is the BBS spec out of IETF, and that spec (as mentioned by Dave) already describes it's relationship to the various academic papers.

**Comment by ad-Orange** [comment]
In response to dlongley:
The name BBS+ was originally used to refer to the extension of BBS to multiple attributes [ASM06]. There are obviously different ways of performing the associated necessary ZKP but the idea is the same: extending BBS to signing multi-attributes VC at once. Using the same name to designate both the original version (BBS) and its multi-attribute extension (BBS+) is confusing.

To Brent: I think that one of the main reason why the IETF is referencing BBS instead of BBS+ is because the W3C is referring to BBS. Kind of a catch 22 here…
Maybe we could have a common IETF / W3C to address the issue ?

**Comment by msporny** [comment]
A rationale has been given for why the specification refers to BBS here: https://github.com/w3c/vc-di-bbs/issues/136#issuecomment-1912790204

Unless there is a counter-argument for why that rationale is not valid, we should close this issue. I'm marking this issue as pending close given the rationale provided.
