### ISSUE TITLE
Title of specification doesn't match other data integrity cryptosuites

### ISSUE THREAD

**Issue by brentzundel** [w3c/vc-di-bbs#137]
I briefly searched for an issue tracking that, apologies if this is a duplicate.

There seems to be a mismatch between the titles of the other Data Integrity cryptosuites and this one:
- Data Integrity ECDSA Cryptosuites v1.0
- Data Integrity EdDSA Cryptosuites v1.0
- BBS Cryptosuite v2023

Perhaps the title should be changed to:
- Data Integrity BBS Cryptosuites v1.0

**Comment by msporny** [comment]
Fixed in 70b1bed445de008108b66074606457688c51b382, published here: https://www.w3.org/TR/2024/WD-vc-di-bbs-20240303/

Closing.
