### ISSUE TITLE
Specify the kind of base58 encoding used

### ISSUE THREAD

**Issue by kdenhartog** [w3c/vc-di-bbs#15]
We should modify base58 to specify base58btc encoding. Unfortunately, we don't have a normative reference here, but there is a ietf draft available here. 

https://tools.ietf.org/html/draft-msporny-base58-01

**Comment by decentralgabe** [comment]
The examples I see in the aries go codebase seem to use b64. What are most implementations doing here?

**Comment by OR13** [comment]
We use multibase now
