### ISSUE TITLE
same diagram to show collusion scenarios in 6.2

### ISSUE THREAD

**Issue by jaromil** [w3c/vc-di-bbs#151]
In section 6.2 https://www.w3.org/TR/vc-di-bbs/#selective-disclosure-and-unlinkability the issue of collusion among verifiers is mentioned, but the diagram shown twice is the one about issuer and verifier collusion.

**Comment by Wind4Greg** [comment]
Thanks @jaromil, I linked the wrong diagram. The right diagram is sitting at https://github.com/w3c/vc-di-bbs/blob/main/diagrams/VerifiersCollusion.svg. Will fix.

Greg

**Comment by msporny** [comment]
PR #152 has been merged to address this issue; closing.
