### ISSUE TITLE
Typo & missing check in chapter 3.4.4

### ISSUE THREAD

**Issue by roblesjoel** [w3c/vc-di-bbs#154]
In chapter 3.4.4 there is a typo:

"DataIntegirtyProof" should be "DataIntegrityProof".

Also in the same chapter, there is no check if the "proofConfig.verificationMethod" is set, which in my opinion is as important as checking if "proofConfig.type" is set. (Maybe there is a reason why that check is missing)

**Comment by msporny** [comment]
PR #158 has been merged to address this issue; closing.
