### ISSUE TITLE
Missing attributes in chapter 3.4.5

### ISSUE THREAD

**Issue by roblesjoel** [w3c/vc-di-bbs#155]
In chapter 3.4.5 step 1 it states:

"Initialize proofHash, mandatoryPointers, mandatoryHash, nonMandatory, and hmacKey to the values associated with their property names in hashData."

But hashData only contains proofHash, mandatoryHash, nonMandatory and hmacKey.
Meaning that "mandatoryPointers" is not part of the hash data, and needs to be supplied separately to the algorithm.

**Comment by Wind4Greg** [comment]
Thanks @RockstaYT, I'm trying to clear up where all the "parameters" or "inputs" come from, i.e., do they get passed down from a higher level function, are they already known to one of the entities (issuer, holder, verifier). This came up with the optional features too.

**Comment by msporny** [comment]
PR #156 was merged to address this issue; closing.
