### ISSUE TITLE
No reference to algorithm

### ISSUE THREAD

**Issue by roblesjoel** [w3c/vc-di-bbs#157]
In chapter 3.3.3, step 11 an algorithm "selectJsonLd" is called, but there is no reference to where that algorithm comes from.

In appendix 2 "A.2" the same algorithm is called and is reference to https://www.w3.org/TR/vc-di-ecdsa/
Would be nice if in chapter 3.3.3. there would be a reference to.

**Comment by Wind4Greg** [comment]
Good catch @roblesjoel! Will fix.

**Comment by msporny** [comment]
PR #158 has been merged to address this issue; closing.
