### ISSUE TITLE
Should we switch signature format to base64url without padding?

### ISSUE THREAD

**Issue by kdenhartog** [w3c/vc-di-bbs#16]
Should we switch signature format to base64url without padding? Right now base64 is being used which is not a common encoding scheme within the space. I think it would be useful for us to switch.

**Comment by kdenhartog** [comment]
Correction, after realizing this isn't using JWS detached signatures like other LD Sigs libraries. In either case, I still find it useful to stick with a common encoding format throughout which suggests using base64url w/o padding or base58 which are used in other parts of the stack commonly.

**Comment by tmarkovski** [comment]
It's my impression that this change has already been implemented.

**Comment by kdenhartog** [comment]
In the typescript implementation and the examples it appears that base64 is being used rather than base64url without padding.

Here's a reference to the typescript code that's using base64:
https://github.com/mattrglobal/jsonld-signatures-bbs/search?q=Base64&unscoped_q=Base64

Here's a reference to an example that uses base64 with padding:
https://github.com/w3c-ccg/ldp-bbs2020/blob/c60931f14120a9ce6b476fd471a15369a88e755a/index.html#L835

**Comment by kdenhartog** [comment]
Related discussion: 

> Should this have ` "@type": "https://w3id.org/security#multibase"` or not? Not sure what `BbsBlsSignature2020` uses for `proofValue`. But `Ed25519Signature2020` should have `proofValue` defined that way. This implies not defining it at the top level so that each suite can define it separately.

_Originally posted by @dlongley in https://github.com/w3c-ccg/security-vocab/pull/78#discussion_r530583389_

After looking at what other suites are doing, I'm thinking it would be valuable for us to consider switching this to multibase format.

**Comment by decentralgabe** [comment]
I'd like this to just be specified as std url encoding without padding

**Comment by kdenhartog** [comment]
I'm +0 to what gets done with this, seems reasonable to go with b64url no padding or multibase to me.

**Comment by OR13** [comment]
AFAIK, we don't need to do anything now, since proofValue is multibase. Closing.
