### ISSUE TITLE
Unused variable

### ISSUE THREAD

**Issue by roblesjoel** [w3c/vc-di-bbs#164]
Hey again,

In chapter 3.4.7 step 2 _proofConfig_ is defined, but never used.
My guess is, that it was defined so it can be passed to the algo in chapter 3.3.8, but instead of passing _proofConfig_, _proof_ (which is defined in step 3) is passed, as in step 2 of chapter 3.3.8 the proofValue is needed, which _proofConfig_ does not contain

**Comment by Wind4Greg** [comment]
Hi @roblesjoel, yes it seems that step 2 "Let proofConfig be a copy of securedDocument.proof with proofValue removed. " is not needed. I'll remove it.

Thanks Greg

**Comment by msporny** [comment]
PR #165 was raised to address this issue and has been merged, closing.
