### ISSUE TITLE
Signature type doesn't specify if it's the `+` version

### ISSUE THREAD

**Issue by kdenhartog** [w3c/vc-di-bbs#17]
Currently the signature type is defined as `BBSSignature2020` which is a uniquely different signature scheme then the one used which is BBS+ signature scheme. If we don't expect the non modified version to be used. 

I'd suggest renaming to `BBSPlusSignature2020` in this case to avoid actually using a `+` character which may lead to odd behaviors in implementations across different programming languages.

**Comment by tplooker** [comment]
@mikelodder7 is best position to answer this, the conversation we had was that calling them BBS is accurate.

**Comment by mikelodder7** [comment]
@kdenhartog what do you mean their vastly different?

**Comment by OR13** [comment]
Closing, stale... and the current draft is still broken related to this, I will do a PR to reset it.
