### ISSUE TITLE
Base proof serialization algorithm does not need proof options nor a normative statement about them

### ISSUE THREAD

**Issue by dlongley** [w3c/vc-di-bbs#172]
The base proof serialization algorithm does not use proof options -- so it can be removed as a parameter and so can a confusing normative statement:

> The proof options MUST contain a type identifier for the [cryptographic suite](https://www.w3.org/TR/vc-data-integrity/#dfn-cryptosuite) (type) and MAY contain a cryptosuite identifier (cryptosuite).

https://w3c.github.io/vc-di-bbs/#base-proof-serialization-bbs-2023

The base proof serialization algorithm is called from the [create base proof algorithm](https://w3c.github.io/vc-di-bbs/#create-base-proof-bbs-2023) which will use and validate proof options (which will ensure that both `type` and `cryptosuite` are appropriately set). So I think we can just remove proof options and the unnecessary/incorrect normative statement about it from the base proof serialization algorithm.

**Comment by msporny** [comment]
PR #173 has been merged to address this issue. Closing.
