### ISSUE TITLE
Adjust indexes?

### ISSUE THREAD

**Issue by brianorwhatever** [w3c/vc-di-bbs#192]
I noticed in the test vectors it mentions adjusting the indexes that are being selected to match the reveal document.. but I don't remember doing that in the implementation. Did I accomplish that in a step I wasn't aware of or is it missing from the algorithms?

**Comment by dlongley** [comment]
Indexes are computed in [`createDisclosureData`](https://w3c.github.io/vc-di-bbs/#createdisclosuredata), steps 7 and 8.

**Comment by brianorwhatever** [comment]
Yep got it, thanks
