### ISSUE TITLE
How to know if a credential is a full disclosure?

### ISSUE THREAD

**Issue by brianorwhatever** [w3c/vc-di-bbs#194]
If the holder is to never present the base VC it feels like it would be valuable information for a verifier to know that they have received a derived proof that is a full disclosure.

There is probably something technical with the indexes that can help them determine it but I wonder if this information should be easily accessible or at least specified in this spec.

**Comment by dlongley** [comment]
> If the holder is to never present the base VC it feels like it would be valuable information for a verifier to know that they have received a derived proof that is a full disclosure.

Hmm, adding any additional primitives to control this seems to imply it would be for a scenario where the verifier would be asking: "Did you tell me everything in your credential or not? If you didn't tell me everything, you need to do that ... no matter what it is."

Unless I'm mistaken about that being the target scenario -- then I don't think that's a valid use case and seems to favor oversharing / sounds like it encourages privacy violations to me. If a verifier happens to be able to tell that whatever they asked for was everything in the credential (by looking at the indexes as you say), I don't think that's an issue, but I don't think we want to encourage verifiers to be able to "ask for everything". If a verifier wants to use an implementation that can tell them more easily whether "everything was revealed or not" -- then that's their perogative.

**Comment by brianorwhatever** [comment]
Ya I am thinking more about the latter case where the data is already
available to them without any new primitives. If it’s already technically
available I think it should be easily available.

**Comment by Wind4Greg** [comment]
Hi @brianorwhatever and @dlongley this information is embedded in BBS proofs but **not** made available from the APIs in the BBS signature scheme spec. In the Proof Verification https://www.ietf.org/archive/id/draft-irtf-cfrg-bbs-signatures-06.html#name-proof-verification-proofver the value **U** represents the number of undisclosed BBS messages, while the **R** value is the number of revealed messages.

Since its not in the BBS API I'm not inclined to add it to the VC-DI-BBS spec. Thoughts?

**Comment by brianorwhatever** [comment]
ok yeah if it isn't exposed at the signature scheme API level I think it's fine to leave it off then. Thank you @Wind4Greg
