### ISSUE TITLE
Define BLS signature/commitment format

### ISSUE THREAD

**Issue by tplooker** [w3c/vc-di-bbs#2]
In BBS+ signature a commitment from the subject is included which is a commitment to their private key (or linked secret). We must define this format such that it could be represented in a DID document.

One of the active decisions is whether we can use a known generator point for this, such that the generator point does not have to be communicated as apart of the signature. Similar to how BLS and other elliptic curve public keys use known points.

**Comment by tmarkovski** [comment]
Should this also include blinded signature format? Or can that process be extrapolated from the signature document?

**Comment by tplooker** [comment]
@tmarkovski usually you do not put a signature in something like a did document you put the material required to verify a signature there.

Conceptually we have been toying with the best way to describe the concept, let me know if the following makes any sense.

At present in the spec we have defined two cryptographic suites BbsBlsSignature2020 BbsBlsSignatureProof2020 and with these we can achieve selective disclosure, however not all of our privacy goals are meet in the sense that the mechanism for which a subject of a signature (credential) can authenticate requires them to disclose a correlating identifier in the credential (e.g a DID), I often refer credentials that operate in this manner as ones that feature did based subject authentication. 

To avoid this unwanted disclosure of an identifier but still have credential presentations involve subject authentication via proving possession of a key we must essentially define another subject authentication mechanism.

The way we intend to achieve this is by having another two cryptographic suites defined called BbsBlsBoundSignature2020 BbsBlsBoundSignatureProof2020 where both of these suites feature a commitment to a private key held by the signature (credential) subject, for which they prove knowledge of when deriving proofs without ever directly revealing the private key, nor a unique identifier for them.

How does it work? Take the following example

Alice wants a credential from Faber College so she creates a DID that features a `Bls12381G1` public key suitable for being issued a credential featuring a `BbsBlsBoundSignature2020`, her did doc might look a little like the following

```
{
  "@context": "https://www.w3.org/ns/did/v1",
  "id": "did:example:123456789abcdefghi",
  "authentication": [{
  "id": "did:example:123456789abcdefghi#test",
  "type": "Bls12381G1Key2020",
  "controller": "did:example:123456789abcdefghi",
  "publicKeyBase58": "4N9Kg9BxmDXtf2QgRH2j1UfFAcQAmgu9Xpwe2fLbSNQHPQHBK5dHrQfFvexvux"
}]
}
```

Where Faber Colleges might look like this

```
{
  "@context": "https://www.w3.org/ns/did/v1",
  "id": "did:example:5687970abcdefghi",
  "assertionMethod": [{
  "id": "did:example:5687970abcdefghi#test",
  "type": "Bls12381G2Key2020",
  "controller": "did:example:5687970abcdefghi",
  "publicKeyBase58": "oqpWYKaZD9M1Kbe94BVXpr8WTdFBNZyKv48cziTiQUeuhm7sBhCABMyYG4kcMrseC68YTFFgyhiNeBKjzdKk9MiRWuLv5H4FFujQsQK2KTAtzU8qTBiZqBHMmnLF4PL7Ytu"
}]
}
```

This would allow faber to issue a credential that looks something like the following

```
{
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://www.w3.org/2018/credentials/examples/v1"
    ],
    "type": ["VerifiableCredential", "AlumniCredential"],
    "issuer": "https://example.edu/issuers/565049",
    "issuanceDate": "2010-01-01T19:73:24Z",
    "credentialSubject": {
      "givenName": "Alice",
      "familyName": "Adams",
      "alumniOf": {
        "id": "did:example:c276e12ec21ebfeb1f712ebc6f1",
        "name": [{
          "value": "Example University",
          "lang": "en"
        }, {
          "value": "Exemple d'Université",
          "lang": "fr"
        }]
      }
    },
    "proof": {
    "type": "BbsBlsBoundSignature2020",
    "verificationMethod": "did:example:5687970abcdefghi#test",
    "subjectAuthenticationMethod": "did:example:123456789abcdefghi#test",
    "proofPurpose": "assertionMethod",
    "proofValue": "pTy8PJCw93RrD+X55McbjHfrlW5SJYNhF84Eggafnlb2CH8QtfXfNsTnVuTQp8UfKKbKqOp6ASwv2kmKtXJJpK+n7+mNKMbeBqw/fuwbu5w/QjvCgYZH3WhlZq6zTmRN9MwO1lQOxntcnKP8xmaoAw=="
  }
  }
```

Where the term `subjectAuthenticationMethod` needs to be defined and never revealed in derived proofs.

When Alice goes to present this credential she might derive a proof that looks like the following

```
{
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://www.w3.org/2018/credentials/examples/v1"
    ],
    "type": ["VerifiableCredential", "AlumniCredential"],
    "issuer": "https://example.edu/issuers/565049",
    "issuanceDate": "2010-01-01T19:73:24Z",
    "credentialSubject": {
      "alumniOf": {
        "id": "did:example:c276e12ec21ebfeb1f712ebc6f1",
        "name": [{
          "value": "Example University",
          "lang": "en"
        }, {
          "value": "Exemple d'Université",
          "lang": "fr"
        }]
      }
    },
    "proof": {
    "type": "BbsBlsBoundSignatureProof2020",
    "verificationMethod": "did:example:5687970abcdefghi#test",
    "proofPurpose": "assertionMethod",
    "proofValue": "pTy8PJCw93RrD+X55McbjHfrlW5SJYNhF84Eggafnlb2CH8QtfXfNsTnVuTQp8UfKKbKqOp6ASwv2kmKtXJJpK+n7+mNKMbeBqw/fuwbu5w/QjvCgYZH3WhlZq6zTmRN9MwO1lQOxntcnKP8xmaoAw==",
    "nonce": "37pdwue1a8FWLqgwCd0QJ0IJTFhp609KtxeCTWZGnfAVE+sOBDffYez+TY/bmVy+6z4="
  }
  }
```

Where in order to be able to derive the proof she would have had to possess the private key associated to `did:example:123456789abcdefghi#test` and a verifier verifying the derive proof could prove this binding to the un-revealed key pair exists but does not know the public key nor the private key or the did that its associated to.

**Comment by tplooker** [comment]
@tmarkovski above is really a starting effort to document how exactly we see this working and I realise it is potentially an expansion or pivot away from your original question.

**Comment by tmarkovski** [comment]
@tplooker Thanks for the explanation, this makes sense. It's similar to what I was asking, if a signature suite will be defined for blinded commitment and blinded signature. In the current BBS+ API (at least the FFI one) the linked secret feature can be solved through the blinding commitment API. However, this process will require application level conventions and multiple proofs in the final derived document. It seems using a blinded key on a known curve is a much cleaner approach with a specific purpose.
My next question is then, should the spec still allow applications to utilize blinding capabilities outside linked secret scenarios, where a prover may potentially have multiple blinded statements. This would mean disclosing the blinding factor in the proof.

For example a suite `BbsBlsBlindedCommitment2020`:
```
{
   "type": "BbsBlsBlindedCommitment2020",
   "blindingFactorBase58": "...",
   "blindedIndices": [ 0, 1 ],
   "proofValue": "..."
}
``` 

And the signed document.

```
{
   "type": "BbsBlsBlindedSignature2020",
   "proofValue": "..."
}
``` 

But now that I said this out loud I realize that constructing blinded messages on the issuer side in JSON-LD would be impossible and why the approach you're taking makes sense.

Looking forward to the updated spec!

**Comment by suutaku** [comment]
it's still in progress？

**Comment by OR13** [comment]
This work has proceeded at IETF.

https://datatracker.ietf.org/doc/draft-irtf-cfrg-bbs-signatures/
