### ISSUE TITLE
Required reveal statements

### ISSUE THREAD

**Issue by tplooker** [w3c/vc-di-bbs#23]
As per section [4.2.5](https://mattrglobal.github.io/jsonld-signatures-bbs-spec/#required-reveal-statements) the term `requiredRevealStatements` is defined that allows the signer of the original assertion to indicate which statements in the sign assertion must always be revealed in a derived proof. The statement is signed by the issuer and a verifier of a derived proof must check for its existence in any derived proofs and also validate that the correct statements have been revealed.

The outstanding question is how to best represent this value, presently in the spec it is defined as an array, however when this is normalised, each element in the array becomes a seperate statement which is not required, we would prefer the requiredRevealStatements manifest as a single statement in the normalised form.

Options 

1. Use a JSON literal array (JSONLD 1.1 supports JSON literals)
2. Encode the array values in some string delimited representation

**Comment by OR13** [comment]
I suggest `@json` literals

**Comment by tplooker** [comment]
The alternative is to use a bit stream stringified as base64, for example say there are 10 statements and the issuer would like to enforce the reveal of the first 5 statements this bit stream would be the following `1111100000` which is the base64 stringified as an attribute in the proof that must be carried through in any derived proofs

**Comment by tplooker** [comment]
This would be more in-line with how we are proposing to simplify revealed statements representation in #22

**Comment by OR13** [comment]
We need to cover mandatory to disclose proof members for the crypto suite that requires them.

**Comment by Wind4Greg** [comment]
Addressed in updated document (PR https://github.com/w3c/vc-di-bbs/pull/99).
