### ISSUE TITLE
Require certain statements to be revealed in a proof

### ISSUE THREAD

**Issue by tplooker** [w3c/vc-di-bbs#28]
Cross linking a relevant issue and discussion on this topic from a reference implementation of the spec, see [here](https://github.com/mattrglobal/jsonld-signatures-bbs/issues/12).

In general as the draft stands we have already assumed option 2 as the approach, but the background discussion here is good context.

**Comment by Wind4Greg** [comment]
Addressed in updated document (PR https://github.com/w3c/vc-di-bbs/pull/99).
