### ISSUE TITLE
Document the rationale for the signers public key in G2 over G1

### ISSUE THREAD

**Issue by tplooker** [w3c/vc-di-bbs#35]
The spec to some extent should aim to document some of the rationale around key decisions that have been made in reference to BBS+ signatures, the below at least aims to capture some of this thinking to date.

BBS+ signatures depend on a pairing friendly elliptic curve (we use BLS12-381), in general one of the things that makes a pairing friendly curve special and allows us to create BBS+ signatures is the fact that the curve defines two sub groups G1 and G2, these are essentially regions in the curve definition for which curve operations can be performed. For instance because these two sub groups exist it is valid with a single private key to have two public keys one in G1 and another in G2. When it comes to applying BLS12-381 to BBS+ signatures we must pick which group the signer (issuer) of the signature must use. The tradeoff to be aware of here when selecting which group to use can be summarised as the following

- Signer Public Key in G2 - Public keys are larger (96) and signatures are smaller (112) and faster to sign/verify 
- Signer Public Key in G1 - Public keys are smaller (48) and signatures are larger (160) and slower to sign/verify 

Essentially depending on how you want to optimise BBS+ signatures influences which option you choose, for our definition we have chosen to have the signers public key in G2 because we assume that a single signer is likely to produce many signatures and therefore optimising the speed of this operation and the size of the signature outweighs having a larger public key representation.

For that reason all signer public keys are of type `Bls12381G2Key` and all messages and commitments that are signed in the production of a BBS+ signature are made in the G1 field.

**Comment by tmarkovski** [comment]
If any, document private key security differences (or implications) between G1 and G2.

**Comment by tplooker** [comment]
Good question, ping @mikelodder7 to confirm but to my knowledge no, the main tradeoffs are as I have described above

**Comment by mikelodder7** [comment]
No security is the same for each field

**Comment by OR13** [comment]
This should be closed, we should cite the IETF draft for key representations.

**Comment by OR13** [comment]
Pending close for 1 week, no objections, closing
