### ISSUE TITLE
Qualify the proofValue term definition with @type of https://w3id.org/security#multibase

### ISSUE THREAD

**Issue by tplooker** [w3c/vc-di-bbs#42]
With the type of this value set on both the BBS+ Signature and Signature Proof technologies like CBOR-LD can apply a codec to compress the values representation in binary

**Comment by tplooker** [comment]
This would be a breaking change to the suite, so I would rather address it in a new 2021 cryptographic suite.

**Comment by OR13** [comment]
We seem to have taken this change, based on the current section @msporny authored. I am going to close this.
