### ISSUE TITLE
Should credential id change for derived proofs

### ISSUE THREAD

**Issue by OR13** [w3c/vc-di-bbs#45]
Originally noted here: https://github.com/w3c-ccg/universal-wallet-interop-spec/issues/73#issuecomment-808153631

by @sudeshrshetty 

From an information modeling perspective, does it make sense that a `selective disclosure capable credential` and `derived disclosure credential` should have the same `id`? I think so, but it obviously makes the ID none unique, which can cause problems...

Note:

```
"id": "http://example.gov/credentials/3732",
```

In this concrete example:

```json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1",
    "https://w3id.org/security/bbs/v1"
  ],
  "id": "http://example.gov/credentials/3732",
  "type": [
    "VerifiableCredential",
    "UniversityDegreeCredential"
  ],
  "issuanceDate": "2020-03-10T04:24:12.164Z",
  "credentialSubject": {
    "id": "did:key:z5TcESXuYUE9aZWYwSdrUEGK1HNQFHyTt4aVpaCTVZcDXQmUheFwfNZmRksaAbBneNm5KyE52SdJeRCN1g6PJmF31GsHWwFiqUDujvasK3wTiDr3vvkYwEJHt7H5RGEKYEp1ErtQtcEBgsgY2DA9JZkHj1J9HZ8MRDTguAhoFtR4aTBQhgnkP4SwVbxDYMEZoF2TMYn3s#zUC7LTa4hWtaE9YKyDsMVGiRNqPMN3s4rjBdB3MFi6PcVWReNfR72y3oGW2NhNcaKNVhMobh7aHp8oZB3qdJCs7RebM2xsodrSm8MmePbN25NTGcpjkJMwKbcWfYDX7eHCJjPGM",
    "degree": {
      "type": "BachelorDegree",
      "name": "Bachelor of Science and Arts"
    }
  },
  "issuer": "did:key:zUC724vuGvHpnCGFG1qqpXb81SiBLu3KLSqVzenwEZNPoY35i2Bscb8DLaVwHvRFs6F2NkNNXRcPWvqnPDUd9ukdjLkjZd3u9zzL4wDZDUpkPAatLDGLEYVo8kkAzuAKJQMr7N2",
  "proof": {
    "type": "BbsBlsSignature2020",
    "created": "2021-02-23T19:36:07Z",
    "proofPurpose": "assertionMethod",
    "proofValue": "qSjCNJzoDV3hv3gBPoUNN9m5lj8saDBBxC0iDHuFTXXz4PbbUhecmn/L3rPoGuySNatqC4I8VE22xQy0RAowIxoZCC+B2mZQIAb+/JGlXeAlWgEQc71WipfvsfqSn+KmR/rN1FREOy3rtSltyQ92rA==",
    "verificationMethod": "did:key:zUC724vuGvHpnCGFG1qqpXb81SiBLu3KLSqVzenwEZNPoY35i2Bscb8DLaVwHvRFs6F2NkNNXRcPWvqnPDUd9ukdjLkjZd3u9zzL4wDZDUpkPAatLDGLEYVo8kkAzuAKJQMr7N2#zUC724vuGvHpnCGFG1qqpXb81SiBLu3KLSqVzenwEZNPoY35i2Bscb8DLaVwHvRFs6F2NkNNXRcPWvqnPDUd9ukdjLkjZd3u9zzL4wDZDUpkPAatLDGLEYVo8kkAzuAKJQMr7N2"
  }
}
```

```json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1",
    "https://w3id.org/security/bbs/v1"
  ],
  "id": "http://example.gov/credentials/3732",
  "type": [
    "UniversityDegreeCredential",
    "VerifiableCredential"
  ],
  "credentialSubject": {
    "id": "did:key:z5TcESXuYUE9aZWYwSdrUEGK1HNQFHyTt4aVpaCTVZcDXQmUheFwfNZmRksaAbBneNm5KyE52SdJeRCN1g6PJmF31GsHWwFiqUDujvasK3wTiDr3vvkYwEJHt7H5RGEKYEp1ErtQtcEBgsgY2DA9JZkHj1J9HZ8MRDTguAhoFtR4aTBQhgnkP4SwVbxDYMEZoF2TMYn3s#zUC7LTa4hWtaE9YKyDsMVGiRNqPMN3s4rjBdB3MFi6PcVWReNfR72y3oGW2NhNcaKNVhMobh7aHp8oZB3qdJCs7RebM2xsodrSm8MmePbN25NTGcpjkJMwKbcWfYDX7eHCJjPGM",
    "degree": {
      "id": "urn:bnid:_:c14n0",
      "type": "BachelorDegree",
      "name": "Bachelor of Science and Arts"
    }
  },
  "issuanceDate": "2020-03-10T04:24:12.164Z",
  "issuer": "did:key:zUC724vuGvHpnCGFG1qqpXb81SiBLu3KLSqVzenwEZNPoY35i2Bscb8DLaVwHvRFs6F2NkNNXRcPWvqnPDUd9ukdjLkjZd3u9zzL4wDZDUpkPAatLDGLEYVo8kkAzuAKJQMr7N2",
  "proof": {
    "type": "BbsBlsSignatureProof2020",
    "created": "2021-02-23T19:37:24Z",
    "nonce": "lEixQKDQvRecCifKl789TQj+Ii6YWDLSwn3AxR0VpPJ1QV5htod/0VCchVf1zVM0y2E=",
    "proofPurpose": "assertionMethod",
    "proofValue": "AAwP/4nFun/RtaXtUVTppUimMRTcEROs3gbjh9iqjGQAsvD+ne2uzME26gY4zNBcMKpvyLD4I6UGm8ATKLQI4OUiBXHNCQZI4YEM5hWI7AzhFXLEEVDFL0Gzr4S04PvcJsmV74BqST8iI1HUO2TCjdT1LkhgPabP/Zy8IpnbWUtLZO1t76NFwCV8+R1YpOozTNKRQQAAAHSpyGry6Rx3PRuOZUeqk4iGFq67iHSiBybjo6muud7aUyCxd9AW3onTlV2Nxz8AJD0AAAACB3FmuAUcklAj5cdSdw7VY57y7p4VmfPCKaEp1SSJTJRZXiE2xUqDntend+tkq+jjHhLCk56zk5GoZzr280IeuLne4WgpB2kNN7n5dqRpy4+UkS5+kiorLtKiJuWhk+OFTiB8jFlTbm0dH3O3tm5CzQAAAAIhY6I8vQ96tdSoyGy09wEMCdWzB06GElVHeQhWVw8fukq1dUAwWRXmZKT8kxDNAlp2NS7fXpEGXZ9fF7+c1IJp",
    "verificationMethod": "did:key:zUC724vuGvHpnCGFG1qqpXb81SiBLu3KLSqVzenwEZNPoY35i2Bscb8DLaVwHvRFs6F2NkNNXRcPWvqnPDUd9ukdjLkjZd3u9zzL4wDZDUpkPAatLDGLEYVo8kkAzuAKJQMr7N2#zUC724vuGvHpnCGFG1qqpXb81SiBLu3KLSqVzenwEZNPoY35i2Bscb8DLaVwHvRFs6F2NkNNXRcPWvqnPDUd9ukdjLkjZd3u9zzL4wDZDUpkPAatLDGLEYVo8kkAzuAKJQMr7N2"
  }
}
```

**Comment by OR13** [comment]
@tplooker @msporny @dlongley any issue with this or comment we should make in the spec? 

Seems like at a minimum we should warn consumers of `BbsBlsSignatureProof2020` about non-uniqueness of `id`.

**Comment by dlongley** [comment]
I also think it makes sense for the `id` to be the same. Aren't the derived credentials ephemeral anyway? I'm not sure why those would be stored but I haven't had the same contact with the problem space as others have yet. I think a warning about how, since the derived credential is really just a subset of information about the same credential (selective disclosure), it has the same `id`.

**Comment by brentzundel** [comment]
imo, if present, the derived credential ID should be the same as the origin cred's credential ID, but also that in most cases it should not be present in the derived credential at all.

**Comment by dlongley** [comment]
> imo, if present, the derived credential ID should be the same as the origin cred's credential ID, but also that in most cases it should not be present in the derived credential at all.

I think "most cases" is too hard to judge. There are use cases for both. Sometimes you want a correlation handle on the VC (if one is not provided, you'll just need to substitute another or the interaction won't be sufficiently secure), other times you're dealing with, for example, short-lived/non-revocable credentials where such an identifier is not useful and the correlation it brings is undesirable.

**Comment by brentzundel** [comment]
@dlongley totally agree there are cases for both, but if it is possible to get the security that is needed without providing a correlating identifier, then it is best to not disclose the credential ID even in the case of long-lived/revocable credentials. I say "most cases" not out of dogmatic adherence to principle, but rather from the belief that in most cases it should be possible to provide the assurances required by a verifier without requiring the holder to disclose identifiers.

regardless, I think we're in agreement on this issue: the credential ID should be the same whether the credential attributes have been selectively disclosed for presentation or not.

**Comment by tplooker** [comment]
> Seems like at a minimum we should warn consumers of BbsBlsSignatureProof2020 about non-uniqueness of id.

Agreed.

Currently the way the algorithm works, because of the underlying usage of RDF Dataset Normalization if you have a credential with an id, any derived credential will need to reveal that id. However if you don't have an id then there is nothing to reveal.

**Comment by brentzundel** [comment]
I had a thought this weekend. Revealing it probably only betrays my lack of understanding of RDF.
Would a derived credential be considered a subgraph of the RDF graph that is the source credential?
If so, should a sub-graph have the same ID as the graph?
Am I even making any sense?

**Comment by OR13** [comment]
@brentzundel my understand is that retaining the same `id` is consistent with the general pattern of use.

I think the proposal should be:

1. Warn users not to disclose `credential.id` unless required to do so.
2. Warn users that it likely won't be unique which shouldn't be a problem since the derived proof SHOULD be only used ephemerally.

The problem may be more of an issue for verifiers who store credentials... if the `id` is missing how will they index he credentials? If its present, what happens if I present a different disclosure of the same credential to the same verifier in the future?

**Comment by dlongley** [comment]
The ID we're talking about is for the VC, which is not a graph but there are statements about it that can be presented in a graph. Those statements may be selectively disclosed if you're using BBS+. So one graph may have N statements and another may have N + M. But those statements are about the same VC, so the ID should be the same, IMO. Again, it's also fine if the VC has no ID -- as @tplooker said.

**Comment by brentzundel** [comment]
Makes sense, thanks for clarifying.

**Comment by kdenhartog** [comment]
If we changed the ID during proof generation wouldn't that break verification anyways because the signature would no longer be bound to the original document? In other words, wouldn't changing the ID be essentially breaking the integrity of the document.

**Comment by brianorwhatever** [comment]
I believe this question only has one answer. A derived credential should have the id of the credential itself as it is the same credential and not a new one. Ideally this derivation flow should be analogous to showing someone a paper document with some of the information redacted.

**Comment by TallTed** [comment]
I do not believe `ex:derivedFrom` is the same relation as `owl:sameAs`.

A Derived Credential -- i.e., *partial* information, *some* properties, from a Verifiable Credential, maybe even some properties *based on but not actually the same as* properties in the VC -- contained in a Verifiable Presentation is not the same as the original Verifiable Credential (with all properties), and giving this Derived Credential the same ID still does not make sense to me (I know, I've said I was leaning toward accepting it, and perhaps even did, some while ago, in a different issue on a different repo, but the concerns I had then have not dissipated).

It *may* make sense to include properties of a Derived Credential (such as `ex:IDofDC ex:derivedFrom ex:IDofOriginalVC . ex:IDofOriginalVC a ex:VS, ex:lease`) in a Verifiable Presentation (which is focused on, perhaps, `ex:proofOfResidence` for the purpose of getting a Passport), which may make it possible for the Verifier to *request* other details or even the entirety of the original (possibly from the original Issuer, possibly from the Holder/Presenter, which does not guarantee delivery thereof, nor even acknowledgement that it exists -- depending on the Requesting Party)....

*At minimum*, a Derived Credential *must* have a different rdf:type than the original Verifiable Credential.  In this case, the DC *might* have the same ID as the original VC -- but how does a Verifier (or more troublingly, an additional Holder) handle receiving and possibly needing to retain two or more DCs with the same ID but with different properties of the Subject contained therein?

I am sorry to say that I see too many pitfalls to giving DCs the same ID as the original VC to accept this as MUST nor even SHOULD.  MAY *might* be acceptable for some specific usage scenarios, but there must be cautions (vis, those I've raised above) alongside that MAY.  I have not convinced myself that MUST NOT is appropriate, but omitting the cautions from the MAY would take me in that direction.

**Comment by OR13** [comment]
@TallTed thanks.

At least in terms of the mechanics of the suite.

I believe you could choose not to disclose the `credential.id`... so its possible that derivations might not have the same `id`.... 

as others have pointed out, not revealing `credential.id` might be a best practice here.

It seems like the proposal is IF the derived credential has an `id` it MUST be the same (cryptographic requirement of verifying a signature)... but it's likely it's a mistake to ever disclose this field.

**Comment by TimoGlastra** [comment]
> I believe you could choose not to disclose the `credential.id`... so its possible that derivations might not have the same `id`....

As I understand you can't NOT disclose the `credential.id` due to how JSON-LD works. 

From Tobias' comment above:

> Currently the way the algorithm works, because of the underlying usage of RDF Dataset Normalization if you have a credential with an id, any derived credential will need to reveal that id. However if you don't have an id then there is nothing to reveal.

**Comment by dlongley** [comment]
My understanding is that some important constraints of the BBS+ crypto and RDF are:

1. If the VC has an ID, it MUST be disclosed if any of the other attributes about the VC are disclosed. This is because the signed RDF triples/quads for the attributes include the ID itself in the RDF subject position.
2. You can't *add* new triples/quads/attributes that were not signed by the issuer.

I expect that this rules out nearly all of what @TallTed has proposed as one way forward.

**Comment by OR13** [comment]
@TimoGlastra thanks... then that is a bit sad... I see the problem. better to make the `id` safe to disclose.

**Comment by TimoGlastra** [comment]
> better to make the `id` safe to disclose.

Another approach would be to use another property instead of `id` if you really need a selectively disclosable identifier. Such as the `identifier` property in citizen vocab (https://w3c-ccg.github.io/citizenship-vocab/#identifier)

**Comment by kdenhartog** [comment]
> > better to make the `id` safe to disclose.
> 
> Another approach would be to use another property instead of `id` if you really need a selectively disclosable identifier. Such as the `identifier` property in citizen vocab (https://w3c-ccg.github.io/citizenship-vocab/#identifier)

I could see this as a viable solution for generic LDPs, but likely is going to break some processing logic for LDPs that are also VCs. If we go this route, we'll likely need to make modifications to the VC spec which makes me hesitant towards that approach.

**Comment by OR13** [comment]
Closing this, we'll need to address when we discuss blank node processing.
