### ISSUE TITLE
Remove required reveal statements from 2020 suite

### ISSUE THREAD

**Issue by TimoGlastra** [w3c/vc-di-bbs#50]
During the BBS+ IIW session the topic of required reveal statements came up.

I think the agreement was to remove the property from the 2020 suite. 

Is this correct?

**Comment by brentzundel** [comment]
That was my understanding

**Comment by kdenhartog** [comment]
I've assigned this to myself. I can take it.

**Comment by OR13** [comment]
This seems pretty stale, I am going to close. The entire proof section is wrong currently.
