### ISSUE TITLE
Mention the `proofValue` and `nonce` values must be base64 encoded

### ISSUE THREAD

**Issue by TimoGlastra** [w3c/vc-di-bbs#51]
As the title suggests. It is not clear from reading the spec that the values must be base64 encoded

**Comment by kdenhartog** [comment]
Agree the encoding should be normatively stated. I think it may be useful for us to look at multibase encoding or base64url no padding as well which is discussed in #16

**Comment by OR13** [comment]
This is stale,  proofValue must be multibase.
