### ISSUE TITLE
Add support for domain proof

### ISSUE THREAD

**Issue by tplooker** [w3c/vc-di-bbs#6]
As a relying party who receives BBS Proofs, I must be able to enable a means in which to detect whether I have seen the credential that has been used to derive the proof before. This cannot be achieved using globally correlatable identifiers, instead a commitment to the linked secret should be generated where the generator value is the has of the relying party identifier. This enables the relying party to validate the commitment and the commitment will be consistent for the same linked secret overtime.

**Comment by OR13** [comment]
AFAIK, this is not yet supported in the IETF documents, so it can't be supported here.

**Comment by OR13** [comment]
Pending close for 1 week, no objections, closing
