### ISSUE TITLE
LDP BBS+ Signatures using JSON Pointer normalization

### ISSUE THREAD

**Issue by jkbpvsc** [w3c/vc-di-bbs#63]
In the scope of our [work item](https://github.com/w3c-ccg/community/issues/204), we are planning to introduce a new canonicalization method with JSON Pointer normalization for use with LDP BBS+ Signatures.

What is the best approach for introducing this change in the LDP BBS+ Signatures specification?

We can either extend the existing [LDP BBS+ Signatures 2020 specification](https://w3c-ccg.github.io/ldp-bbs2020/) with an additional canonicalization algorithm alongside URDNA2015. The implication is that this will modify the existing BBS+ context with additional terms: `canonicalizationAlgorithm` defined in the security vocab.

Or we can fork the specification into LDP BBS+ Signatures 2021, and add the canonicalization algorithm there. This new scheme would be backwards compatible with LDP BBS+ Signatures 2020.

**Comment by OR13** [comment]
Seems out of scope, I am going to close.
