### ISSUE TITLE
Believe it is a typo in chapter 6.1.1 step 1

### ISSUE THREAD

**Issue by echenknox** [w3c/vc-di-bbs#65]
In [chapter 6.1.1 step 1 ](https://w3c-ccg.github.io/ldp-bbs2020/#create-verify-data-algorithm-0)
It states as

> Obtain a **blind** message which is a commitment to a secret value as described in [[BBS](https://w3c-ccg.github.io/ldp-bbs2020/#bib-bbs)] section 3.9. This is the recipient binding commitment.

From the context, there's no mention of the blind message. And It doesn't look like it is related to blind signature here. I believe it meant to use the word "bind".

**Comment by OR13** [comment]
AFAIK, this has never been implemented.

**Comment by TallTed** [comment]
Looks like a typo to me, too. Fix before close, @OR13?

**Comment by OR13** [comment]
There is a PR up to remove the entire section, which has never been implemented, afaik.

**Comment by OR13** [comment]
Closing this, as the section has been removed.
