### ISSUE TITLE
w3id.org links are broken after repository migration

### ISSUE THREAD

**Issue by ctomc** [w3c/vc-di-bbs#74]
Broken links: 
https://w3id.org/security/bbs
https://w3id.org/security/bbs/v1
https://w3id.org/bbs
https://w3id.org/bbs/v1

I've opened PR to address the change https://github.com/perma-id/w3id.org/pull/3251 but needs to be approved by maintainers of this repository in order to be merged.

**Comment by OR13** [comment]
This has been fixed (Thank you!!!)
