### ISSUE TITLE
Add Support For Bound Signatures

### ISSUE THREAD

**Issue by OR13** [w3c/vc-di-bbs#79]
This is the best citation we have so for for the topic:

https://github.com/BasileiosKal/bbs-bound-signatures

This issue is to discuss possible approaches to commenting on it.

Here are a few high level options to discuss, if we get consensus I suggest we close this issue and open a new one, focused on the agreed approach.

#### Option 0

Don't comment on Bound Signatures at all.

#### Option 1

Mention them in privacy / security considerations and refer to ongoing work indirectly.

#### Option 2

Mention them in privacy / security considerations and add an informative section in the appendix that points at IETF drafts.

#### Option 3

Define a Data Integrity Proof Suite and JSON Serialization for Bound Signatures in this document, but don't refer to draft outside this document.

#### Option 4

Define a Data Integrity Proof Suite and JSON Serialization for Bound Signatures in this document, AND refer to draft outside this document.

**Comment by OR13** [comment]
cc @tplooker @dlongley @msporny

I am currently a fan on Option 1 or 2, based on the current state of the bound signature work.

I think options 3 and 4 will have process issues that come with them.

discuss :)

**Comment by Wind4Greg** [comment]
Since BBS bound signatures is not yet a IRTF ID and will most likely come after work on BBS Blind signatures. Recommend not mentioning bound signatures. See PR https://github.com/w3c/vc-di-bbs/pull/101 for privacy considerations and PR https://github.com/w3c/vc-di-bbs/pull/100 for security considerations.
