### ISSUE TITLE
Use CBOR to compress `proof`

### ISSUE THREAD

**Issue by OR13** [w3c/vc-di-bbs#80]
@msporny said:

> One thing we will probably want to do is fold things like `disclosed` and `generators` into the `proofValue` and make `proofValue` a CBOR structure of some kind. 

- https://github.com/w3c/vc-di-bbs/issues/75#issuecomment-1523452462

Lets discuss making `proof` more compact in this issue.

**Comment by OR13** [comment]
I don't think we should muck with CBOR in this working group, it seems fine to treat those fields as members of the JSON `proof` object, and then there is no need to grow the tool chain beyond  what we have today.

**Comment by Wind4Greg** [comment]
CBOR is now used to compress base and derived proofs.
