### ISSUE TITLE
Hosted JSON-LD context should expose itself as `ld+json` instead of `json`

### ISSUE THREAD

**Issue by j-steinbach** [w3c/vc-di-bbs#90]
Hi, I am using a [library](https://github.com/mattrglobal/jsonld-signatures-bbs) that depends on the `vc-di-bbs` JSON-LD context.

Unfortunately the `content-type` of https://w3c.github.io/vc-di-bbs/contexts/v1/ seems to be currently set to `application/json`. 

This in turn cause me [issues](https://github.com/rubensworks/jsonld-context-parser.js/issues/44#issuecomment-1660482546) when parsing the JSON-LD.

> 2023-08-01T15:08:40.059Z [BasicResponseWriter] {Primary} error: Response error: Failed to load remote context https://w3id.org/security/bbs/v1: Unsupported JSON-LD media type application/json

Now I am not 100% sure if I am barking at the correct tree, but changing the application type to `application/ld+json` ([IANA](https://www.iana.org/assignments/media-types/application/ld+json)) should fix the parsing issues.

![image](https://github.com/w3c/vc-di-bbs/assets/69524139/f796d37b-c27e-4dd3-8ed3-55a010cf795b)

**Comment by dlongley** [comment]
My understanding is that `application/json` should be accepted by JSON-LD document loaders:

https://www.w3.org/TR/json-ld11-api/#loaddocumentcallback

So it sounds like there may be a bug with the loader you're using (i.e., it's too strict).

**Comment by j-steinbach** [comment]
Yes, makes sense. I'll forward that.

Nevertheless, ignoring any too-strict loaders on my end, does it make sense for the document in this repository to not be `ld+json`? Is there a reason to stick with `json`?

**Comment by dlongley** [comment]
@j-steinbach,

I imagine there may be challenges with making it do that with github pages (I'm not sure though). It's also the case that that context will likely be deprecated and no longer used as the VCWG is updated that cryptosuite to get it to W3C Recommendation status. In other words, expect it to change and very soon if it's going to become a standard through W3C. The expectation is that it will no longer need its own context -- as the newer data integrity cryptosuite mechanism doesn't require a separate context from either the core data integrity context or the core VC v2 context.

**Comment by j-steinbach** [comment]
Thanks for the explanation. I think I'll then wait for the official recommendation and use a band-aid fix in the mean time. 

I don't think I have anything to add, as I also don't know how to do that with Github pages -- which means this issue can be closed.

**Comment by tmarkovski** [comment]
FWIW, I have ran into a similar problem when I used the [dotnetrdf](https://www.nuget.org/packages/dotNetRDF/) which was too strict content type checking. I used a [small fix](https://github.com/trinsic-id/dotnetrdf/pull/1/files) to get around it. Not sure which one you are using, but I think many libraries may be operating with the initial JSON-LD specifications that weren't as permissive.

**Comment by Wind4Greg** [comment]
Updated specification uses data integrity (https://w3c.github.io/vc-data-integrity/) approach and hence BBS is now specified via the `cryptosuite` string value, i.e., "bbs-2023". See https://w3c.github.io/vc-di-bbs/.
