### ISSUE TITLE
Remove references to MULTIBASE and MULTICODEC

### ISSUE THREAD

**Issue by selfissued** [w3c/vc-di-bbs#92]
MULTIBASE and MULTICODEC are not standards.  Please replace uses of them with normative text defining the contents any fields using them.

This is related to https://github.com/w3c/vc-data-integrity/issues/191.

**Comment by msporny** [comment]
There is no PR yet as @OR13 has stepped down as an Editor and it's not clear if @tplooker is committed to completing this work item. If the proposal that @Wind4Greg and I take over editorship of the specification is adopted, we will apply the same changes to remove the references to the IETF I-Ds that you approved in the other PRs to this specification.

**Comment by Wind4Greg** [comment]
Adopted text and approach from [vc-di-ecdsa](https://w3c.github.io/vc-di-ecdsa/#ecdsa-sd-2023). Normative dependencies have been removed per prior approved approach.
