### ISSUE TITLE
Reuse ECDSA-SD Primitives where Possible, Use JSON Pointers

### ISSUE THREAD

**Issue by Wind4Greg** [w3c/vc-di-bbs#93]
Hi all in particular @OR13 and @tplooker I'd really like to see this work move forward and contribute but the current draft does a lot of its own JSON-LD related processing which is outside my expertise. I recently completed a walk through and generation of ECDSA-SD test vectors (see the example code at [ECDSA-SD Test Vectors](https://github.com/Wind4Greg/ECDSA-SD-TestVectors) where I also tried out these techniques on BBS (see the BBS sub-directory of the Test Vector Code). There was also a discussion of what needed to be modified on this discussion chain: https://github.com/w3c/vc-di-bbs/issues/84#issuecomment-1719585365

My suggestions and what I could contribute is:

* Replace use of JSON-LD framing for Mandatory and Selective specification with easy to use (and standard) **JSON Pointers** as done in [ECDSA-SD](https://w3c.github.io/vc-di-ecdsa/#ecdsa-sd-2023)
* Reuse almost all the selective disclosure functions from [ECDSA-SD](https://w3c.github.io/vc-di-ecdsa/#selective-disclosure-functions), i.e., some of the HMAC stuff needs to be substituted with other functionality per the above cited discussion. An example is in my sample code mentioned above.
* Follow the same basic approaches used in [ecdsa-sd-2023 functions](https://w3c.github.io/vc-di-ecdsa/#ecdsa-sd-2023-functions) to come up with a corresponding set of function specific for BBS. An example is in my sample code mentioned above.
* Finally modify the high level functions in [ecdsa-sd-2023](https://w3c.github.io/vc-di-ecdsa/#ecdsa-sd-2023) to produce a BBS equivalent. An example is in my sample code mentioned above.

Some high level notes on mapping to BBS can be found [here](https://github.com/Wind4Greg/ECDSA-SD-TestVectors/tree/main#test-vector-generation-for-sd-primitivesbbs).  

Authors of the ECDSA specification @msporny and @dlongley what do you think of such an approach? *Note* that the SD primitives are modular enough so that **no changes** would be required to the ECDSA draft.

**Comment by dlongley** [comment]
@Wind4Greg,

> Authors of the ECDSA specification @msporny and @dlongley what do you think of such an approach? _Note_ that the SD primitives are modular enough so that **no changes** would be required to the ECDSA draft.

This sounds like a great plan to move things forward, so +1 from me. Excellent to hear that the base SD functions in ECDSA-SD can just be referenced and reused here with a few additions for BBS as needed.

**Comment by msporny** [comment]
> Authors of the ECDSA specification @msporny and @dlongley what do you think of such an approach?

+1 from me as well, feels like a solid plan forward which re-uses all the work we had to do for ECDSA-SD.

**Comment by Wind4Greg** [comment]
Hi folks interested in BBS (@msporny, @dlongley, @brentzundel) and current editors (@OR13 and @tplooker) I did a review of the current BBS document and compared it to the structure of [vc-di-ecdsa](https://github.com/w3c/vc-di-ecdsa) and [vc-di-eddsa](https://github.com/w3c/vc-di-eddsa) and would recommend the following major update (a single PR rather than a bunch of small PRs)

## VC-DI-BBS Specification Proposed Edits

* Align Terminology section with that of ECDSA plus any needed terms
* Remove section "Verification Methods"/JsonWebKey as this is defined in Data Integrity Spec
* Update section "Verification Methods"/MultiKey to explicitly state how to form representation, i.e., appropriate BLS12-381 public key in group G2 header value.
* Add a section on "Proof Representations" and in it put the section on "Data Integrity Proof"
  * *Note* There will only be one cryptosuite value "bbs-2023" this is in line with the [Conventions for Naming Cryptography Suites](https://w3c.github.io/vc-data-integrity/#conventions-for-naming-cryptography-suites) from the Data Integrity Spec. We will tell the difference between *BBS signatures* and *BBS proofs* by the serialization headers used in the `proofValue` attribute. This is the approach taken in ECDSA-SD. So need to modify the existing "Data Integrity Proof" section accordingly (It gets simpler and smaller)
* Restructure the "Algorithms" section with the following subsections:
  * "Selective Disclosure Functions" -- Only one or two new functions specific to BBS to preserve unlinkability property. Otherwise will reference those in ECDSA-SD.
  * "bbs-2023 Functions": This would include many but not all of the following suitably modified for BBS: serializeSignData, serializeBaseProofValue, parseBaseProofValue, createDisclosureData,compressLabelMap, decompressLabelMap, serializeDerivedProofValue, parseDerivedProofValue,createVerifyData. *Note* we don't necessarily need all of these due to BBS's built in capabilities.
  * "bbs-2023": This would include functions modified for BBS such as: Add Base Proof, Base Proof Transformation, Base Proof Hashing, Base Proof Configuration, Base Proof Serialization, Add Derived Proof, Verify Derived Proof
* The section on "Privacy Considerations" needs to be filled in and should include advice to issuers and others on the "unlinkable" property of BBS proofs and how higher layer artifacts can diminish this property. This would be somewhat based on the discussions in https://github.com/w3c/vc-di-bbs/issues/84#issuecomment-1719585365.
* Add a "Test Vectors" section with subsections for "Base Proof" and "Derived Proof". The code to produce these exists as mentioned previously.
* **General Action item**: There are actually two BBS suites in the IETF draft. One based on SHAKE-256, and the other based on SHA-256. We should quickly survey interested parties and choose **one**.
* **Optional**: Would like to add a relatively short *informative* description of the processing that leads to the "messages" and related information that gets fed into the BBS "API" to further understanding, security review, and privacy review with respect to linkability. This would not be "tutorial" material but material to aid those not familiar with the details of verifiable credential technology in security/privacy assessments.

If I hear some rough consensus on this approach to moving this forward I can start working on a PR. However, we seem to need an active editor or two. I can help with editing if folks want to go with this approach.

Cheers Greg

**Comment by dlongley** [comment]
@Wind4Greg,

+1 to the above plan, it sounds great, and thank you for your efforts here. I think anything else can be iterated on once we've got this new PR in, approved, and merged that brings this spec up to date per the above. If you need a decision in that PR on the hash function I'd go with SHA-256 since native implementations for it are more commonly available -- but this is another thing we can consider more fully later (I don't think it should block initial progress).

**Comment by msporny** [comment]
+1 to the proposed plan to move forward. I can help edit as well, but will prioritize: Data Integrity specs, VC Core Data Model and vc-di-eddsa and vc-di-ecdsa, BitStringStatusList, and finally vc-di-bbs. The sooner we can get the first three groups to CR, the sooner I can shift a lot of my focus to vc-di-bbs.
