### ISSUE TITLE
Apparent inconsistency in `proofValue` examples & normative multibase statement

### ISSUE THREAD

**Issue by AFlowOfCode** [w3c/vc-di-bbs#95]
In both the [bbs-signature-2023](https://www.w3.org/TR/vc-di-bbs/#bbs-signature-2023) and [bbs-proof-2023](https://www.w3.org/TR/vc-di-bbs/#bbs-proof-2023) sections, there is a normative statement:

> The proofValue property of the proof MUST be a detached BBS Signature [...] encoded according to [MULTIBASE] using the base64 base encoding with no padding.

The examples immediately following the respective statements are the same and look like `"proofValue": "uU6i3dTz5yFfWJ...."`.
The [multibase spec](https://datatracker.ietf.org/doc/html/draft-multiformats-multibase-08#name-the-multibase-algorithms-re) indicates that the character `u` is for usage with base64url encoding, whereas `m` indicates base64 encoding.

There seems to be a contradiction here which leaves me unsure of which encoding should actually be used with multibase. Could someone enlighten me as to which is correct: the statement, or the example?

Thank you.

**Comment by dlongley** [comment]
I think this is now out of date? I couldn't find any references to just base64 -- only references to base64url-no-pad, which is correct and what `u` indicates as a multibase header. I think everything is consistent now and we can close this.

**Comment by Wind4Greg** [comment]
This is out of date. The current specification only uses CBOR and base64 see https://w3c.github.io/vc-di-bbs/#serializebaseproofvalue and https://w3c.github.io/vc-di-bbs/#serializederivedproofvalue.

**Comment by dlongley** [comment]
> The current specification only uses CBOR and base64 ...

Just for clarity around "base64" (since this issue is specifically about "base64" vs. "base64url"), the spec uses *base64url-no-pad* and the multibase prefix of `u` to signal that. All is well now and we should close this in 7 days.

**Comment by AFlowOfCode** [comment]
This issue is indeed out of date and no longer relevant since the November 4th set of rewrites. Specifically it was obsoleted by commit https://github.com/w3c/vc-di-bbs/commit/59e86c58183821558995a1d6c7a996a10e47ad5d.
